title: "bits4ilor's blog"
author: "bits4ilor"
description: "┌─[bitsailor@zion]-[~]<br/>└ $ ⎕ "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"

# Layout

sidebar: true               # show a sidebar instead of the usual header
show_excerpts: true          # show article excerpts on the home page
show_related: false           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: true            # always keep the header dark
minimal: true               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "tools.md", icon: tools}
  - {file: "archive.html", icon: archive}
  - {file: "README.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/bitsailor"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/bitsailor"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/bitsailor"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jemoji

